# Generated by Django 5.2.6 on 2026-09-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
