# Generated by Django 5.2.6 on 2026-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_posts', '0002_alter_post_author'),
        ('apps_users', '0002_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='apps_posts.post'),
        ),
    ]
