# Generated by Django 5.2.6 on 2026-09-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0003_user_posts_liked'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='apps.users',
        ),
    ]
