# Generated by Django 5.2.6 on 2026-09-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_posts', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='apps.posts',
        ),
    ]
